// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  try {
    config = require('../config.json');
  } catch (_error) {}

  if (!(typeof (config != null ? config.port : void 0) === 'number' && typeof (config != null ? config.targets : void 0) === 'object')) {
    if (process.argv[2] === 'config') {
      config = {};
    } else {
      console.log('ERROR: configuration required. Run:');
      console.log('vhostd config');
      process.exit(1);
    }
  }

  module.exports = config;

}).call(this);
