// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  config = require('./config');

  module.exports = function(req) {
    var Target, data, item, requested_host, target, _i, _len, _ref;
    Target = function(target) {
      var host, port, _ref;
      _ref = target.split(':'), host = _ref[0], port = _ref[1];
      return {
        host: host,
        port: Number(port)
      };
    };
    requested_host = (req.headers.host + ':').split(':')[0];
    _ref = config.getTargets();
    for (target in _ref) {
      data = _ref[target];
      if (data === requested_host) {
        return new Target(target);
      } else if (typeof data === 'object') {
        for (_i = 0, _len = data.length; _i < _len; _i++) {
          item = data[_i];
          if (item === requested_host) {
            return new Target(target);
          }
        }
      }
    }
    return null;
  };

}).call(this);
