// Generated by CoffeeScript 1.6.3
(function() {
  var get_target, log;

  get_target = require('./get_target');

  log = require('./log');

  module.exports = function(req, res, proxy) {
    var err, target;
    try {
      target = get_target(req);
      if ((target != null ? target.host : void 0) && (target != null ? target.port : void 0)) {
        log(req, target);
        return proxy.proxyRequest(req, res, target);
      } else {
        res.writeHead(404, {
          'Content-Type': 'text/plain'
        });
        res.write('Missing page\n');
        res.end();
        return console.log('    TARGET ERROR', req.headers);
      }
    } catch (_error) {
      err = _error;
      return console.log('    ERROR: ', err);
    }
  };

}).call(this);
