// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(req, target, protocol) {
    if (protocol == null) {
      protocol = 'http';
    }
    return console.log('[' + (new Date).toUTCString() + ']', req.method, protocol + '://' + req.headers.host + req.url, '->', target.host + ':' + target.port);
  };

}).call(this);
