#!/usr/bin/env node
// Generated by CoffeeScript 1.6.3
(function() {
  var e, task;

  try {
    task = require('./tasks/' + (process.argv[2] || 'server'));
  } catch (_error) {
    e = _error;
    process.stderr.write('ERROR: invalid task: "' + process.argv[2] + '"\n\n');
  }

  task.run();

}).call(this);
