// Generated by CoffeeScript 1.6.3
(function() {
  var get_target, log;

  get_target = require('./get_target');

  log = require('./log');

  module.exports = function(req, socket, head) {
    var err, target;
    try {
      target = get_target(req);
      if ((target != null ? target.host : void 0) && (target != null ? target.port : void 0)) {
        log(req, target, 'ws');
        return server.proxy.proxyWebSocketRequest(req, socket, head, target);
      } else {
        throw new Error('No valid target for websocket');
      }
    } catch (_error) {
      err = _error;
      return console.log('    WS-ERROR: ', JSON.stringify(err));
    }
  };

}).call(this);
