// Generated by CoffeeScript 1.6.3
(function() {
  var config, fs, httpProxy, http_route, log, ws_route;

  fs = require('fs');

  httpProxy = require('http-proxy');

  config = require('../config');

  http_route = require('../http_route');

  log = require('../log');

  ws_route = require('../ws_route');

  module.exports.run = function() {
    require('./test-privilege');
    module.exports.server = httpProxy.createServer(http_route).on('upgrade', ws_route).listen(config.port);
    return console.log('[' + (new Date).toUTCString() + '] listening @ port', config.port);
  };

}).call(this);
