// Generated by CoffeeScript 1.6.3
(function() {
  var config, fs, httpProxy, http_route, restart_requested, server, server_running, start, stop, stop_requested, ws_route;

  require('./require-root');

  fs = require('fs');

  httpProxy = require('http-proxy');

  config = require('../lib/config');

  http_route = require('../lib/http_route');

  ws_route = require('../lib/ws_route');

  server = null;

  restart_requested = null;

  stop_requested = false;

  server_running = false;

  start = function() {
    server = httpProxy.createServer(http_route).on('upgrade', ws_route).listen(config.getPort());
    server_running = true;
    return console.log('[' + (new Date).toUTCString() + '] listening @ port', config.getPort());
  };

  stop = function(restart) {
    restart_requested = restart_requested || restart;
    if (server_running && !stop_requested) {
      stop_requested = true;
      console.log('[' + (new Date).toUTCString() + '] stopping service ' + '(this may take a while)');
      return server.close(function() {
        console.log('[' + (new Date).toUTCString() + '] stopped');
        server_running = false;
        stop_requested = false;
        if (restart_requested) {
          restart_requested = false;
          return start();
        }
      });
    } else if (!server_running && restart_requested) {
      restart_requested = false;
      return start();
    }
  };

  module.exports.run = function() {
    config.attachStartEvent(function() {
      return stop(true);
    });
    config.attachStopEvent(stop);
    if (config.isRunnable()) {
      return start();
    }
  };

}).call(this);
