// Generated by CoffeeScript 1.6.3
(function() {
  var child_process;

  child_process = require('child_process');

  module.exports = function(callback) {
    return child_process.exec('ps aux', function(err, stdout, stderr) {
      var line, pid, pid_line, _i, _len, _ref;
      if (err) {
        return callback(err);
      }
      _ref = stdout.split('\n');
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        line = _ref[_i];
        if (line.indexOf('vhostd-service') > -1) {
          pid_line = line;
          break;
        }
      }
      if (!pid_line) {
        return callback(null, null);
      }
      while (pid_line.indexOf('  ') > -1) {
        pid_line = pid_line.replace('  ', ' ');
      }
      pid = pid_line.split(' ')[1];
      if (!(pid > 0 && pid < 65536 && pid % 1 === 0)) {
        return callback(null, null);
      }
      return callback(null, Number(pid));
    });
  };

}).call(this);
