// Generated by CoffeeScript 1.6.3
(function() {
  var config, server_log, stderr;

  config = require('./config');

  server_log = require('./server_log');

  stderr = require('./stderr');

  module.exports = function(req, res, proxy) {
    var err, requested_host, target, _ref;
    try {
      requested_host = String((req != null ? (_ref = req.headers) != null ? _ref.host : void 0 : void 0) + ':').split(':')[0];
      target = config.getTarget(requested_host);
      if ((target != null ? target.host : void 0) && (target != null ? target.port : void 0)) {
        server_log(req, target);
        return proxy.proxyRequest(req, res, target);
      } else {
        res.writeHead(404, {
          'Content-Type': 'text/plain'
        });
        res.write('Missing page\n');
        res.end();
        return stderr('TARGET ERROR:', JSON.stringify(req.headers));
      }
    } catch (_error) {
      err = _error;
      return stderr('ERROR:', JSON.stringify(err));
    }
  };

}).call(this);
