// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(req, target, protocol) {
    var date, day, dd, hour, min, month, ms, sec, year;
    if (protocol == null) {
      protocol = 'http';
    }
    dd = function(str) {
      str = String(str);
      switch (str.length) {
        case 0:
          return '00';
        case 1:
          return '0' + str;
        case 2:
          return str;
        default:
          return str.substr(str.lenth - 2);
      }
    };
    date = new Date;
    year = date.getFullYear();
    month = dd(date.getMonth() + 1);
    day = dd(date.getDate());
    hour = dd(date.getHours());
    min = dd(date.getMinutes());
    sec = dd(date.getSeconds());
    ms = (date.getMilliseconds() + '00').substr(0, 3);
    return '[' + year + '-' + month + '-' + day + ' ' + hour + ':' + min + ':' + sec + '.' + ms + ']';
  };

}).call(this);
