// Generated by CoffeeScript 1.6.3
(function() {
  var config, server_log, stderr;

  config = require('./config');

  server_log = require('./log');

  stderr = require('./stderr');

  module.exports = function(req, socket, head) {
    var err, requested_host, target, _ref;
    try {
      requested_host = String((req != null ? (_ref = req.headers) != null ? _ref.host : void 0 : void 0) + ':').split(':')[0];
      target = config.getTarget(requested_host);
      if ((target != null ? target.host : void 0) && (target != null ? target.port : void 0)) {
        server_log(req, target, 'ws');
        return server.proxy.proxyWebSocketRequest(req, socket, head, target);
      } else {
        throw new Error('No valid target for websocket');
      }
    } catch (_error) {
      err = _error;
      return stderr('ERROR:', JSON.stringify(err));
    }
  };

}).call(this);
